version: 2
updates:

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "7:00"
    timezone: "Australia/Brisbane"

- package-ecosystem: maven
  directories:
   - "**/*"
  schedule:
    interval: daily
    time: "7:00"
    timezone: "Australia/Brisbane"
  groups:
    jackson:
      patterns:
        - "jackson*"
  open-pull-requests-limit: 10
