name: Package Publish GitHub
run-name: "Deploy from \"${{ github.ref_name }}\" to version \"${{ github.event.inputs.releaseVersion }}\" by @${{ github.actor }}, dryrun: ${{ github.event.inputs.publish == 'No' }}"

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      publish:
        type: choice
        description: Publish Version
        options:
          - 'No'
          - 'Yes'

jobs:
  publish:
    name: "Publish version"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write
      actions: write
      id-token: write
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
      #When run workflow_dispatch is set and publish is 'Yes', default for workflow_dispatch is No so you can't trigger without a double action
      DO_DEPLOYMENT: ${{ github.event_name == 'workflow_dispatch'  && github.event.inputs.publish == 'Yes' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          fetch-depth: 3

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Dump event context for debugging
        continue-on-error: true  # Debugging output only, and this annoyingly fails when the commit messge has a (
        run: |
          echo '${{ github.event_name }} for ${{ github.ref_type }} ${{ github.ref_name }} or ${{ github.event.ref }}'
          # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
          echo 'github.event:'
          echo '${{ toJSON(github.event) }}'

      - name: Dump github context for debugging
        continue-on-error: true  # Debugging output only, and this annoyingly fails when the commit message has a (
        run: |
          echo '${{ toJSON(github) }}'

      - name: Try to set a master password
        run: |
          MASTERPWD=$(openssl rand -base64 25)
          echo "<settingsSecurity> <master>$(mvn --encrypt-master-password "$MASTERPWD")</master></settingsSecurity>" > $HOME/.m2/settings-security.xml
          # echo "MASTERPWD=\"$MASTERPWD\"" >> $GITHUB_ENV
          # The master password isn't actually used, but the maven-gpg-plugin complains otherwise.

      - name: Git & Maven Status
        run: |
          mvn -version
          git remote -v
          git status --untracked-files --ignored
          git log -3 --no-color --decorate

      - name: Mvn Effective POM
        run: mvn -Pgithub -N help:effective-pom
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Mvn Effective Settings
        run: mvn -Pgithub -N help:effective-settings
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

      - name: Set up Git username and email
        run: |
          git config --global user.name "${{ vars.GPG_NAME }}"
          git config --global user.email "${{ secrets.GPG_EMAIL }}"
          echo "${{ secrets.GPG_KEY }}" | base64 --decode | gpg --import --no-tty --batch --yes
          #gpg -v --refresh-keys #only needed for external gpg keys
          gpg --list-secret-keys --keyid-format LONG
          git config --global user.signingkey ${{ secrets.GPG_KEY_ID }}
          git config --global commit.gpgSign true
          git config --global tag.gpgSign true
          git config --global gpg.program gpg

      - name: Verify git is clean
        run: |
          git status --untracked-files --ignored
          git log -3 --no-color --decorate
          git clean -f -d

      - name: Publish package
        if: ${{ env.DO_DEPLOYMENT == 'true' }}
        run: mvn -Pgithub  --batch-mode clean deploy -DsignTag=true
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KITEWORKS_BASE_URI: ${{ secrets.KITEWORKS_BASE_URI }}
          KITEWORKS_CLIENT_ID: ${{ secrets.KITEWORKS_CLIENT_ID }}
          KITEWORKS_CLIENT_SECRET: ${{ secrets.KITEWORKS_CLIENT_SECRET }}
          KITEWORKS_SIGNATURE_KEY: ${{ secrets.KITEWORKS_SIGNATURE_KEY }}
          KITEWORKS_USER_ID: ${{ secrets.KITEWORKS_USER_ID }}
          KITEWORKS_CLIENT_APP_SCOPES: ${{ secrets.KITEWORKS_CLIENT_APP_SCOPES }}
          KITEWORKS_REDIRECT_URI: ${{ secrets.KITEWORKS_REDIRECT_URI }}
          KITEWORKS_ACCESS_TOKEN_URI: ${{ secrets.KITEWORKS_ACCESS_TOKEN_URI }}
          KITEWORKS_USERNAME: ${{ secrets.KITEWORKS_USERNAME }}
          KITEWORKS_PASSWORD: ${{ secrets.KITEWORKS_PASSWORD }}
          KITEWORKS_ACTIVITY_LIST_UUID: ${{ secrets.KITEWORKS_ACTIVITY_LIST_UUID }}
          KITEWORKS_ACTIVITY_LIST2_UUID: ${{ secrets.KITEWORKS_ACTIVITY_LIST2_UUID }}

      - name: Cleanup on failure
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ORG: ${{ github.repository_owner }}
          GITHUB_REPO: ${{ github.event.repository.name }}
          RELEASE_VERSION: ${{ github.event.inputs.releaseVersion }}
        run: ./.github/bin/cleanupGitHubMavenPackage.sh

      - name: Git Status after perform
        if: always()
        run: |
          git status
          git log -3 --no-color --decorate

      - name: Git Status after perform, long
        if: always()
        run: |
          git status --untracked-files --ignored

      - name: List target files even if recipe fails
        if: always()
        run: |
          pwd
          ls -ld
          ls -ld target
          find . -type d -name target
          ls -l ./target/checkout/target || true
          ls -l ./target/checkout/commons/target || true

      - name: Publish - Skipped
        if: ${{ env.DO_DEPLOYMENT != 'true' }}
        run: |
          echo "### Publish skipped" >> $GITHUB_STEP_SUMMARY
          echo "DO_DEPLOYMENT( ${{ env.DO_DEPLOYMENT }} ): github.event_name: ${{ github.event_name != 'workflow_dispatch'}} || github.event.inputs.force: ${{ github.event.inputs.force == 'Yes' }}"  >> $GITHUB_STEP_SUMMARY
