name: Package Publish

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      publish:
        type: choice
        description: Publish Version
        options:
          - 'No'
          - 'Yes'
      releaseVersion:
        description: 'Release version'
        required: true
        default: '1.0.0'
      developmentVersion:
        description: 'Development version'
        required: true
        default: '1.0.1-SNAPSHOT'

jobs:
  publish:
    name: "Release version ${{ github.event.inputs.releaseversion }}"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
      #When run workflow_dispatch is set and publish is 'Yes', default for workflow_dispatch is No so you can't trigger without a double action
      DO_DEPLOYMENT: ${{ github.event_name == 'workflow_dispatch'  && github.event.inputs.publish == 'Yes' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'maven'

      - name: Build with Maven
        env:
          KITEWORKS_BASE_URI: ${{ secrets.KITEWORKS_BASE_URI }}
          KITEWORKS_CLIENT_ID: ${{ secrets.KITEWORKS_CLIENT_ID }}
          KITEWORKS_CLIENT_SECRET: ${{ secrets.KITEWORKS_CLIENT_SECRET }}
          KITEWORKS_SIGNATURE_KEY: ${{ secrets.KITEWORKS_SIGNATURE_KEY }}
          KITEWORKS_USER_ID: ${{ secrets.KITEWORKS_USER_ID }}
          KITEWORKS_CLIENT_APP_SCOPES: ${{ secrets.KITEWORKS_CLIENT_APP_SCOPES }}
          KITEWORKS_REDIRECT_URI: ${{ secrets.KITEWORKS_REDIRECT_URI }}
          KITEWORKS_ACCESS_TOKEN_URI: ${{ secrets.KITEWORKS_ACCESS_TOKEN_URI }}
        run: mvn clean install  -Dspring.profiles.active=cicd

      - name: Set up Git username and email
        run: |
          git config --global user.name " ${{ variables.GPG_NAME }}"
          git config --global user.email "${{ secrets.GPG_EMAIL }}"
          echo "${{ secrets.GPG_KEY }}" | gpg --batch --import
          git config --global user.signingkey ${{ secrets.GPG_KEY_ID }}
          git config --global commit.gpgSign true
          git config --global gpg.program gpg
        env:
          ssh-deploy-key: ${{ secrets.DEPLOY_KEY }}
          ssh-gpg-email: ${{ secrets.GPG_EMAIL }}
          ssh-gpg-key: ${{ secrets.GPG_KEY }}
          ssh-gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          ssh-gpg-name: ${{ variables.GPG_NAME }}

      - name: "Verify GPG setup"
        run: gpg --list-keys

      - name: Increment poms
        run: echo "do"
        env:
          ssh-deploy-key: ${{ secrets.DEPLOY_KEY }}
          ssh-gpg-email: ${{ secrets.GPG_EMAIL }}
          ssh-gpg-key: ${{ secrets.GPG_KEY }}
          ssh-gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          ssh-gpg-name: ${{ variables.GPG_NAME }}

      - name: Publish package
        if: ${{ env.DO_DEPLOYMENT == 'true' }}
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KITEWORKS_BASE_URI: ${{ secrets.KITEWORKS_BASE_URI }}
          KITEWORKS_CLIENT_ID: ${{ secrets.KITEWORKS_CLIENT_ID }}
          KITEWORKS_CLIENT_SECRET: ${{ secrets.KITEWORKS_CLIENT_SECRET }}
          KITEWORKS_SIGNATURE_KEY: ${{ secrets.KITEWORKS_SIGNATURE_KEY }}
          KITEWORKS_USER_ID: ${{ secrets.KITEWORKS_USER_ID }}
          KITEWORKS_CLIENT_APP_SCOPES: ${{ secrets.KITEWORKS_CLIENT_APP_SCOPES }}
          KITEWORKS_REDIRECT_URI: ${{ secrets.KITEWORKS_REDIRECT_URI }}
          KITEWORKS_ACCESS_TOKEN_URI: ${{ secrets.KITEWORKS_ACCESS_TOKEN_URI }}

      - name: Increment workflow defaults
        if: ${{ env.DO_DEPLOYMENT == 'true' }}
        run: |
          ./../bin/versionIncrement.sh
          git push
        

      - name: Publish - Skipped
        if: ${{ env.DO_DEPLOYMENT != 'true' }}
        run: |
          echo "### Publish skipped" >> $GITHUB_STEP_SUMMARY
          echo "DO_DEPLOYMENT( ${{ env.DO_DEPLOYMENT }} ): github.event_name: ${{ github.event_name != 'workflow_dispatch'}} || github.event.inputs.force: ${{ github.event.inputs.force == 'Yes' }}"  >> $GITHUB_STEP_SUMMARY


#      - name: Set up Java for publishing to Maven Central Repository
#        uses: actions/setup-java@v4
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          server-id: ossrh
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#      - name: Publish to the Maven Central Repository
#        run: mvn --batch-mode deploy
#        env:
#          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#          KITEWORKS_BASE_URI: ${{ secrets.KITEWORKS_BASE_URI }}
#          KITEWORKS_CLIENT_ID: ${{ secrets.KITEWORKS_CLIENT_ID }}
#          KITEWORKS_CLIENT_SECRET: ${{ secrets.KITEWORKS_CLIENT_SECRET }}
#          KITEWORKS_SIGNATURE_KEY: ${{ secrets.KITEWORKS_SIGNATURE_KEY }}
#          KITEWORKS_USER_ID: ${{ secrets.KITEWORKS_USER_ID }}
#          KITEWORKS_CLIENT_APP_SCOPES: ${{ secrets.KITEWORKS_CLIENT_APP_SCOPES }}
#          KITEWORKS_REDIRECT_URI: ${{ secrets.KITEWORKS_REDIRECT_URI }}
#          KITEWORKS_ACCESS_TOKEN_URI: ${{ secrets.KITEWORKS_ACCESS_TOKEN_URI }}
