name: Integration Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '21'
        cache: 'maven'

    - name: Build with Maven
      env:
        KITEWORKS_BASE_URI: ${{ secrets.KITEWORKS_BASE_URI }}
        KITEWORKS_CLIENT_ID: ${{ secrets.KITEWORKS_CLIENT_ID }}
        KITEWORKS_CLIENT_SECRET: ${{ secrets.KITEWORKS_CLIENT_SECRET }}
        KITEWORKS_SIGNATURE_KEY: ${{ secrets.KITEWORKS_SIGNATURE_KEY }}
        KITEWORKS_USER_ID: ${{ secrets.KITEWORKS_USER_ID }}
        KITEWORKS_CLIENT_APP_SCOPES: ${{ secrets.KITEWORKS_CLIENT_APP_SCOPES }}
        KITEWORKS_REDIRECT_URI: ${{ secrets.KITEWORKS_REDIRECT_URI }}
        KITEWORKS_ACCESS_TOKEN_URI: ${{ secrets.KITEWORKS_ACCESS_TOKEN_URI }}
        KITEWORKS_USERNAME: ${{ secrets.KITEWORKS_USERNAME }}
        KITEWORKS_PASSWORD: ${{ secrets.KITEWORKS_PASSWORD }}
        KITEWORKS_ACTIVITY_LIST_UUID: ${{ secrets.KITEWORKS_ACTIVITY_LIST_UUID }}
        KITEWORKS_ACTIVITY_LIST2_UUID: ${{ secrets.KITEWORKS_ACTIVITY_LIST2_UUID }}
      run: mvn clean install  -Dspring.profiles.active=cicd -Pskip-gpg-signing

    - name: Package artifacts
      run: |
       mkdir staging
       cp  */target/*.jar staging
       cp -rf */target/*reports staging
       cp -r  */target/generated-sources/openapi/api staging

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: staging
        overwrite: true

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@5b7ee5a21e8674b695313d769f3cbdfd5d4d53a4 #v6.0.0
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/target/**-reports/TEST-*.xml'
        check_name: Test Report

